--------------Tabla temporal----------
create table TT1
(
    NOMBRE_VICTIMA           varchar2(50),
    APELLIDO_VICTIMA         varchar2(50),
    DIRECCION_VICTIMA        varchar2(100),
    FECHA_PRIMERA_SOSPECHA   TIMESTAMP(6),
    FECHA_CONFIRMACION       TIMESTAMP(6),
    FECHA_MUERTE             TIMESTAMP(6),
    ESTADO_VICTIMA           varchar2(50),
    NOMBRE_ASOCIADO          varchar2(50),
    APELLIDO_ASOCIADO        varchar2(50),
    FECHA_CONOCIO            TIMESTAMP(6), 
    CONTACTO_FISICO          varchar2(50),
    FECHA_INICIO_CONTACTO    TIMESTAMP(6),
    FECHA_FIN_CONTACTO       TIMESTAMP(6),
    NOMBRE_HOSPITAL          varchar2(50),
    DIRECCION_HOSPITAL       varchar2(100),
    UBICACION_VICTIMA        varchar(50),
    FECHA_LLEGADA            TIMESTAMP(6),
    FECHA_RETIRO             TIMESTAMP(6),
    TRATAMIENTO              varchar(50),
    EFECTIVIDAD              integer,
    FECHA_INICIO_TRATAMIENTO TIMESTAMP(6),
    FECHA_FIN_TRATAMIENTO    TIMESTAMP(6),
    EFECTIVIDAD_EN_VICTIMA   integer
);

--------------Creacion Hospital------------------

CREATE TABLE Hospital (
id_hospital integer generated by default as identity not null,
nombre_hospital VARCHAR2(100),
direccion_hospital VARCHAR2(200),
primary key (id_hospital)
);

--------------Creacion Victima------------------
CREATE TABLE Victima
(
    id_victima             integer generated by default as identity not null,
    nombre_victima         VARCHAR2(100),
    apellido_victima       VARCHAR2(100),
    direccion_victima      VARCHAR2(200),
    UBICACION_VICTIMA      varchar(50),
    fecha_primera_sospecha TIMESTAMP(6),
    fecha_confirmacion     TIMESTAMP(6),
    fecha_muerte           TIMESTAMP(6),
    Estado_victima         VARCHAR2(100),
    id_hospital            integer,
    primary key (id_victima),
    constraint fk_Hospital_Victima foreign key (id_hospital) references Hospital (id_hospital)
);


--------------Creacion ALLEGADO-----------------------------
CREATE TABLE Allegado(
    id_allegado integer generated by default as identity not null,
    nombre_allegado VARCHAR(100),
    apellido_allegado varchar(100),
    fecha_conocio TIMESTAMP(6),
    primary key (id_allegado)

);
--------------Creacion TIPO CONTACTO-------------
CREATE TABLE TIPO_CONTACTO(
    id_Tipo_contacto integer generated by default as identity not null,
    nombre_tipo_contacto VARCHAR(100),
    primary key (id_Tipo_contacto)

)
----------------- Creacion CONTACTO----------------
CREATE TABLE CONTACTO(
    ID_CONTACTO integer generated by default as identity not null,
    ID_VICTIMA integer ,
    ID_ALLEGADO integer ,
    ID_TIPO_CONTACTO integer,
    FECHA_INICIO TIMESTAMP(6),
    FECHA_FIN TIMESTAMP(6),
    primary key (ID_CONTACTO),
    constraint fk_CONTACTO_VICTIMA foreign key (ID_VICTIMA) references Victima(id_victima),
    constraint fk_CONTACTO_ALLEGADO foreign key  (ID_ALLEGADO) references Allegado(id_allegado),
    constraint fk_CONTACTO_TIPO_CONTACTO foreign key (ID_TIPO_CONTACTO) references TIPO_CONTACTO(id_Tipo_contacto)
);

--------------Creacion TRATAMIENTO--------------
CREATE TABLE Tratamiento (
    Id_Tratamiento integer generated by default as identity not null,
    Nombre VARCHAR2(100) NOT NULL,
    FECHA_INICIO_TRATAMIENTO TIMESTAMP(6),
    FECHA_FIN_TRATAMIENTO TIMESTAMP(6),
    PRIMARY KEY (Id_Tratamiento),
    EFECTIVIDAD  integer,
    EFECTIVIDAD_VICTIMA integer
);


-- Creación de la tabla VictimaTratamiento
CREATE TABLE VictimaTratamiento(
    ID_TRATAMIENTO_VICTIMA integer generated by default as identity not null,
    FECHA                  TIMESTAMP(6),
    ID_TRATAMIENTO         integer                                  not null,
    ID_VICTIMA             integer                                  not null,
    primary key (ID_TRATAMIENTO_VICTIMA),
    constraint fk_TRATAMIENTO_VICTIMA foreign key (ID_TRATAMIENTO) references Tratamiento(Id_Tratamiento),
    constraint fk_VICTIMA_TRATAMIENTO foreign key (ID_VICTIMA) references Victima (id_victima)
);



INSERT INTO Victima (nombre_victima, apellido_victima, direccion_victima, UBICACION_VICTIMA, fecha_primera_sospecha, fecha_confirmacion, fecha_muerte, Estado_victima, id_hospital)
SELECT DISTINCT  NOMBRE_VICTIMA, APELLIDO_VICTIMA, DIRECCION_VICTIMA, UBICACION_VICTIMA, FECHA_PRIMERA_SOSPECHA, FECHA_CONFIRMACION, FECHA_MUERTE, ESTADO_VICTIMA, id_hospital
FROM TT
LEFT JOIN Hospital ON Hospital.nombre_hospital = TT.NOMBRE_HOSPITAL AND Hospital.direccion_hospital = TT.DIRECCION_HOSPITAL;
SELECT COUNT(*) FROM VICTIMA v ;
SELECT * FROM VICTIMA v ;
SELECT COUNT(*) FROM HOSPITAL h  ;
INSERT INTO Allegado (nombre_allegado, apellido_allegado, fecha_conocio)
SELECT DISTINCT  NOMBRE_ASOCIADO, APELLIDO_ASOCIADO, FECHA_CONOCIO
FROM TT;

INSERT INTO TIPO_CONTACTO (nombre_tipo_contacto)
SELECT DISTINCT CONTACTO_FISICO
FROM TT


INSERT INTO CONTACTO (ID_VICTIMA, ID_ALLEGADO, id_Tipo_contacto, FECHA_INICIO, FECHA_FIN)
SELECT v.ID_VICTIMA, a.ID_ALLEGADO, tc.id_Tipo_contacto, TT.FECHA_INICIO_CONTACTO, TT.FECHA_FIN_CONTACTO
FROM TT
LEFT JOIN Victima v ON v.NOMBRE_VICTIMA = TT.NOMBRE_VICTIMA AND v.APELLIDO_VICTIMA = TT.APELLIDO_VICTIMA
LEFT JOIN Allegado a ON a.nombre_allegado = TT.NOMBRE_ASOCIADO AND a.apellido_allegado = TT.APELLIDO_ASOCIADO
LEFT JOIN TIPO_CONTACTO tc ON tc.NOMBRE_TIPO_CONTACTO = TT.CONTACTO_FISICO;

SELECT COUNT(*) FROM CONTACTO c ;

INSERT INTO Tratamiento (Nombre, FECHA_INICIO_TRATAMIENTO, FECHA_FIN_TRATAMIENTO, EFECTIVIDAD, EFECTIVIDAD_VICTIMA)
SELECT TRATAMIENTO, FECHA_INICIO_TRATAMIENTO, FECHA_FIN_TRATAMIENTO, EFECTIVIDAD, EFECTIVIDAD_EN_VICTIMA
FROM TT
WHERE TRATAMIENTO IS NOT NULL;

INSERT INTO VictimaTratamiento (FECHA, ID_TRATAMIENTO, ID_VICTIMA)
SELECT TT.FECHA_INICIO_TRATAMIENTO, T.Id_Tratamiento, V.id_victima
FROM TT 
INNER JOIN Tratamiento T ON TT.TRATAMIENTO = T.Nombre
INNER JOIN Victima V ON V.nombre_victima = TT.NOMBRE_VICTIMA AND V.apellido_victima = TT.APELLIDO_VICTIMA AND V.direccion_victima = TT.DIRECCION_VICTIMA
---------------fin de creacion he insercion de modelo logico------------------------------

-------------consulta 1---------------
SELECT h.nombre_hospital, h.direccion_hospital, COUNT(v.fecha_muerte) AS num_fallecidos
FROM Hospital h
LEFT JOIN Victima v ON h.id_hospital = v.id_hospital
WHERE v.fecha_muerte IS NOT NULL
GROUP BY h.nombre_hospital, h.direccion_hospital;
------------------------consulta 2 ----------------------
SELECT v.nombre_victima, v.apellido_victima
FROM Victima v
INNER JOIN VictimaTratamiento vt ON v.id_victima = vt.id_victima
INNER JOIN Tratamiento t ON vt.id_tratamiento = t.id_tratamiento
WHERE v.estado_victima = 'En cuarentena'
  AND t.nombre = 'Transfusiones de sangre'
  AND t.efectividad_victima > 5; 
 --------------------------consulta 3 funcional ----------------------------
SELECT v.nombre_victima, v.apellido_victima, v.direccion_victima
FROM Victima v
INNER JOIN Contacto c ON v.id_victima = c.id_victima
WHERE v.fecha_muerte IS NOT NULL
GROUP BY v.id_victima, v.nombre_victima, v.apellido_victima, v.direccion_victima
HAVING COUNT(*) > 3;
---------------------consulta 3(tambien funciona) -------------------------
SELECT nombre_victima, apellido_victima, direccion_victima
FROM Victima
WHERE Estado_victima = 'muerte' 
AND id_victima IN (
   SELECT ID_VICTIMA
   FROM Contacto
   GROUP BY ID_VICTIMA
   HAVING COUNT(*) > 3
);

-------------consulta 4-------------------
SELECT v.nombre_victima, v.apellido_victima
FROM Victima v
INNER JOIN Contacto c ON v.id_victima = c.id_victima
WHERE v.estado_victima = 'Suspendida' AND c.id_tipo_contacto = (SELECT id_tipo_contacto FROM Tipo_Contacto WHERE nombre_tipo_contacto = 'Beso')
GROUP BY v.nombre_victima, v.apellido_victima
HAVING COUNT(DISTINCT c.id_allegado) > 2;
-------------consulta 5---------------------------
SELECT v.nombre_victima, v.apellido_victima, COUNT(*) AS cantidad_tratamientos
FROM Victima v
INNER JOIN VictimaTratamiento vt ON v.id_victima = vt.id_victima
INNER JOIN Tratamiento t ON vt.id_tratamiento = t.id_tratamiento
WHERE t.nombre = 'Oxigeno'
GROUP BY v.id_victima, v.nombre_victima, v.apellido_victima
ORDER BY cantidad_tratamientos DESC
FETCH FIRST 5 ROWS ONLY;
-------------------consulta 6-------------------
SELECT DISTINCT  v.nombre_victima, v.apellido_victima, v.fecha_muerte
FROM Victima v
INNER JOIN VictimaTratamiento vt ON v.id_victima = vt.id_victima
INNER JOIN Tratamiento t ON vt.id_tratamiento = t.id_tratamiento
WHERE v.UBICACION_VICTIMA  = '1987 Delphine Well' AND t.nombre = 'Manejo de la presion arterial' AND v.FECHA_MUERTE  IS  NOT NULL 

------------------------otra consulta 7------------------------------
SELECT v.nombre_victima, v.apellido_victima, v.direccion_victima
FROM Victima v
JOIN CONTACTO c ON v.id_victima = c.id_victima
JOIN Allegado a ON c.id_allegado = a.id_allegado
JOIN Hospital h ON v.id_hospital = h.id_hospital
JOIN VictimaTratamiento vt ON v.id_victima = vt.id_victima
JOIN Tratamiento t ON vt.id_tratamiento = t.id_tratamiento
WHERE a.id_allegado IN (
    SELECT c.id_allegado
    FROM CONTACTO c
    GROUP BY c.id_allegado
    HAVING COUNT(*) < 2
)
AND h.id_hospital IS NOT NULL
GROUP BY v.nombre_victima, v.apellido_victima, v.direccion_victima
HAVING COUNT(DISTINCT vt.id_tratamiento) = 2;

----------------------- consulta 7-------------------------
SELECT v.nombre_victima, v.apellido_victima, v.direccion_victima
FROM Victima v
WHERE 
    (SELECT COUNT(*) 
     FROM Contacto c 
     WHERE c.id_victima = v.id_victima) < 2
    AND v.id_hospital IS NOT NULL
    AND v.id_victima IN (
        SELECT vt.id_victima 
        FROM VictimaTratamiento vt 
        GROUP BY vt.id_victima 
        HAVING COUNT(DISTINCT vt.id_tratamiento) = 2
    );

  -----------------------consulta 8------------------------------
   SELECT EXTRACT(MONTH FROM fecha_primera_sospecha) as mes,
    nombre_victima, apellido_victima,
    (SELECT COUNT(*) FROM VictimaTratamiento WHERE id_victima = v.id_victima) as num_tratamientos
FROM Victima v
WHERE
    (SELECT COUNT(*) FROM VictimaTratamiento WHERE id_victima = v.id_victima) = 
        (SELECT MAX(cnt) FROM 
            (SELECT COUNT(*) as cnt FROM VictimaTratamiento GROUP BY id_victima) t)
    OR
    (SELECT COUNT(*) FROM VictimaTratamiento WHERE id_victima = v.id_victima) = 
        (SELECT MIN(cnt) FROM 
            (SELECT COUNT(*) as cnt FROM VictimaTratamiento GROUP BY id_victima) t)
ORDER BY num_tratamientos DESC;



-----------------------consulta 9 ------------------------------
SELECT nombre_victima, apellido_victima, UBICACION_VICTIMA 
FROM Victima
WHERE id_victima IN (
    SELECT c.id_victima
    FROM Contacto c
    JOIN (
        SELECT id_victima, COUNT(DISTINCT id_allegado) AS num_allegados
        FROM Contacto
        WHERE id_victima IN (
            SELECT id_victima
            FROM Victima
            WHERE id_hospital IS NOT NULL
        )
        GROUP BY id_victima
        HAVING COUNT(DISTINCT id_allegado) < 2
    ) a ON c.id_victima = a.id_victima
    WHERE c.id_allegado IN (
        SELECT id_allegado
        FROM Allegado
        WHERE fecha_conocio <= ALL (
            SELECT fecha_conocio
            FROM Contacto
            WHERE id_victima = c.id_victima AND id_allegado = c.id_allegado
        )
    )
    GROUP BY c.id_victima
    HAVING COUNT(*) <= 2
);

-----------------consulta 10 ---------------------------------
SELECT DISTINCT  h.nombre_hospital, c.nombre_tipo_contacto, COUNT(*) * 100.0 / v_count.total AS porcentaje
FROM Hospital h
INNER JOIN Victima v ON h.id_hospital = v.id_hospital
INNER JOIN (
  SELECT id_victima, COUNT(*) AS total
  FROM Contacto
  GROUP BY id_victima
) v_count ON v.id_victima = v_count.id_victima
INNER JOIN (
  SELECT DISTINCT  ID_VICTIMA, ID_TIPO_CONTACTO, COUNT(*) AS cnt
  FROM Contacto
  GROUP BY ID_VICTIMA, ID_TIPO_CONTACTO
) c_count ON v.id_victima = c_count.ID_VICTIMA
INNER JOIN Tipo_Contacto c ON c_count.ID_TIPO_CONTACTO = c.id_tipo_contacto
WHERE c_count.cnt = (
  SELECT MAX(cnt)
  FROM (
    SELECT DISTINCT  ID_VICTIMA, ID_TIPO_CONTACTO, COUNT(*) AS cnt
    FROM Contacto
    GROUP BY ID_VICTIMA, ID_TIPO_CONTACTO
  ) c2
  WHERE c2.ID_VICTIMA = v.id_victima
)
GROUP BY h.nombre_hospital, c.nombre_tipo_contacto, v_count.total
ORDER BY h.nombre_hospital, porcentaje DESC;
--------------ELIMINACION DE MODELO-------------
DROP TABLE VICTIMA;
DROP TABLE HOSPITAL;
DROP TABLE TRATAMIENTO;
DROP TABLE VICTIMATRATAMIENTO ;
DROP TABLE CONTACTO ;
DROP TABLE TIPO_CONTACTO ;
DROP TABLE TT1 ;