logging:
  level:
    com.example.SBD1: DEBUG
spring:
  datasource:
    url: jdbc:oracle:thin:@34.174.139.189:1521:ORCL18
    username: L4MH
    password: l4mh
    driver-class-name: oracle.jdbc.driver.OracleDriver